version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
defaults: &defaults
  docker:
    - image: cimg/base:stable-20.04
    - image: circleci/mysql:8.0.23
      entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
      environment:
        MYSQL_ROOT_PASSWORD: rootpw
        MYSQL_DATABASE: test_varbase
        MYSQL_USER: user
        MYSQL_PASSWORD: passw0rd
commands:
  varbase-build:
    steps:
      - checkout         
      ## Usefull must have utils
      - run:
          name: Usefull must have utils
          command: |
            sudo apt -qq update
            sudo apt -qqy upgrade
            sudo apt -yqq install vim links lynx git diffutils htop curl wget p7zip-full unzip zip sed gcc g++ make libfreetype6-dev libonig-dev libpng-dev xvfb default-mysql-client

      ## Setup Apache2 to PHP7.4
      - run:
          name: Setup Apache2 and PHP7.4
          command: |
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt update
            sudo apt upgrade
            sudo apt install -yqq apache2 php7.4 libapache2-mod-php7.4 php7.4-mbstring php7.4-mysql php7.4-xml php7.4-cgi php7.4-cli php7.4-common php7.4-curl php7.4-gd php7.4-imap php7.4-intl php7.4-pspell php7.4-sqlite3 php7.4-tidy php7.4-opcache php7.4-json php7.4-bz2 php7.4-readline php7.4-xmlrpc php7.4-enchant php7.4-xsl php-all-dev php7.4-zip php7.4-bcmath php-pear
            sudo a2enmod php7.4 headers rewrite env mime expires ssl
            sudo echo 'memory_limit = -1' >> /etc/php/7.4/apache2/php.ini
            sudo echo 'max_execution_time = 1200' >> /etc/php/7.4/apache2/php.ini
            sudo echo 'max_input_time = 180' >> /etc/php/7.4/apache2/php.ini
            sudo echo 'max_input_vars = 10000' >> /etc/php/7.4/apache2/php.ini
            sudo echo 'error_reporting = E_ALL' >> /etc/php/7.4/apache2/php.ini
            sudo echo 'post_max_size = 64M' >> /etc/php/7.4/apache2/php.ini
            sudo echo 'upload_max_filesize = 32M' >> /etc/php/7.4/apache2/php.ini
            sudo echo 'max_file_uploads = 40' >> /etc/php/7.4/apache2/php.ini
            sudo service apache2 restart

      ## Waiting for MySQL to be ready.
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      ## List tool version.
      - run:
          name: List tool version
          command: |
            php --version
            node --version
            java -version
            google-chrome --version
            chromedriver --version
            mysql --version

      ## Install composer ~2.1
      - run:
          name: Install composer ~2.1
          command: |
            sudo curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin/ --filename=composer --1;
            composer --version

      ## Build Varbase with the composer and Install with drush.
      - run:
          name: Build Varbase with the composer and Install with drush
          no_output_timeout: 30m
          command: |
            sudo rm -rf /var/www/html/test/varbase
            cd /var/www/html/test
            composer config -g github-oauth.github.com $GITHUB_TOKEN
            composer create-project vardot/varbase-project:9.0.x-dev varbase --stability dev --no-interaction
            cd /var/www/html/test/varbase
            composer require drupal/core-dev:*
            composer require drush/drush:~10.0
            composer require drupal/drupal-extension:~4.0
            composer require emuse/behat-html-formatter:^0.2.0
            
      ## Point varbase.test at /var/www/html/test/varbase/docroot
      - run:
          name: Point varbase.test at /var/www/html/test/varbase/docroot
          command: |
            sudo a2enmod headers rewrite env mime expires ssl
            sudo cp /home/circleci/project/.circleci/env/varbase.test.conf /etc/apache2/sites-available/varbase.test.conf
            sudo a2ensite varbase.test
            echo 127.0.0.1 varbase.test | sudo tee -a /etc/hosts
            sudo service apache2 restart
            
            
      ## Install Varbase with drush.
      - run:
          name: Install Varbase with drush
          no_output_timeout: 30m
          command: |
            mysql -h 127.0.0.1 -uuser -ppassw0rd -e "DROP DATABASE IF EXISTS test_varbase;CREATE DATABASE test_varbase;"
            cd /var/www/html/test/varbase/docroot
            ../bin/drush site-install varbase --yes --site-name='Varbase Test' --account-name=webmaster --account-pass=dD.123123ddd --account-mail=webmaster@vardot.com --db-url="mysql://user:passw0rd@127.0.0.1/test_varbase" varbase_multilingual_configuration.enable_multilingual=true varbase_extra_components.vmi=true varbase_extra_components.varbase_heroslider_media=true varbase_extra_components.varbase_carousels=true varbase_extra_components.varbase_search=true varbase_extra_components.varbase_blog=true varbase_extra_components.varbase_landing=true varbase_extra_components.varbase_auth=true
            ../bin/drush pm-enable varbase_development --yes
            ../bin/drush pm-enable varbase_styleguide --yes
            ../bin/drush pm-enable varbase_landing --yes
            ../bin/drush pm-enable varbase_media_instagram --yes
            ../bin/drush pm-enable varbase_media_twitter --yes
            ../bin/drush pm-enable varbase_api --yes
            ../bin/drush pm-enable social_auth_google --yes
            ../bin/drush pm-enable social_auth_facebook --yes
            ../bin/drush pm-enable social_auth_linkedin --yes
            ../bin/drush pm-enable varbase_content_planner --yes
            ../bin/drush config-set system.performance css.preprocess 0 --yes
            ../bin/drush config-set system.performance js.preprocess 0 --yes
            ../bin/drush config-set system.logging error_level all --yes
            ../bin/drush cr
            
      ## Install browser tools
      - browser-tools/install-browser-tools

      ## Install Java.
      - run:
          name: Install Java
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-11-jre openjdk-11-jre-headless openjdk-11-jdk openjdk-11-jdk-headless
            
      ## Configure and run the virtual display.
      - run:
          name: Configure and run the virtual display
          command: |
            export DISPLAY=:99
            xvfb :99 -ac -screen 0 1366x768x24 &>/dev/null &
            sleep 3

      ## Run selenium standalone server.
      - run:
          name: Run selenium standalone server
          command: |
            if [[ ! -f /home/circleci/selenium-server-standalone-2.53.1.jar ]]; then wget -O /home/circleci/selenium-server-standalone-2.53.1.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar; fi
            cd /home/circleci/
            java -jar selenium-server-standalone-2.53.1.jar -port 4445 > /home/circleci/selenium.log
          background: true

      ## Automated Functional Acceptance Testing - Step 1 init tests.
      - run:
          name: Automated Functional Acceptance Testing - Step 1 init tests
          no_output_timeout: 30m
          command: |
            cd /var/www/html/test/varbase/docroot/profiles/varbase
            ../../../bin/behat --strict --no-snippets -f pretty -o std tests/features/varbase/step1-init-tests/
jobs:
  varbase-testing-01-website-base-requirements:
    <<: *defaults
    steps:
      - varbase-build
       ## Automated Functional Acceptance Testing group - 01 website base requirements
      - run:
          name: Automated Functional Acceptance Testing group - 01 website base requirements
          no_output_timeout: 30m
          command: |
            cd /var/www/html/test/varbase/docroot/profiles/varbase
            ../../../bin/behat --strict --no-snippets -f pretty -o std tests/features/varbase/step2-apply-tests/01-website-base-requirements/
  varbase-testing-02-user-management-03-admin-management:
    <<: *defaults
    steps:
      - varbase-build
      ## Automated Functional Acceptance Testing group - 02 user management - 03 admin management
      - run:
          name: Automated Functional Acceptance Testing group - 02 user management - 03 admin management
          no_output_timeout: 30m
          command: |
            cd /var/www/html/test/varbase/docroot/profiles/varbase
            ../../../bin/behat --strict --no-snippets -f pretty -o std tests/features/varbase/step2-apply-tests/02-user-management/
            ../../../bin/behat --strict --no-snippets -f pretty -o std tests/features/varbase/step2-apply-tests/03-admin-management/
  varbase-testing-04-content-structure:
    <<: *defaults
    steps:
      - varbase-build
      ## Automated Functional Acceptance Testing group - 04 content structure
      - run:
          name: Automated Functional Acceptance Testing group - 04 content structure
          no_output_timeout: 30m
          command: |
            cd /var/www/html/test/varbase/docroot/profiles/varbase
            ../../../bin/behat --strict --no-snippets -f pretty -o std tests/features/varbase/step2-apply-tests/04-content-structure/
  varbase-testing-05-content-management:
    <<: *defaults
    steps:
      - varbase-build
      ## Automated Functional Acceptance Testing group - 05 content-management
      - run:
          name: Automated Functional Acceptance Testing group - 05 content-management
          no_output_timeout: 30m
          command: |
            cd /var/www/html/test/varbase/docroot/profiles/varbase
            ../../../bin/behat --strict --no-snippets -f pretty -o std tests/features/varbase/step2-apply-tests/05-content-management/

workflows:
  version: 2
  varbase-workflow:
    jobs:
      - varbase-testing-01-website-base-requirements:
          filters:
            tags:
              only: /^9.*/
            branches:
              only: /^9.0.x/
      - varbase-testing-02-user-management-03-admin-management:
          filters:
            tags:
              only: /^9.*/
            branches:
              only: /^9.0.x/
      - varbase-testing-04-content-structure:
          filters:
            tags:
              only: /^9.*/
            branches:
              only: /^9.0.x/
      - varbase-testing-05-content-management:
          filters:
            tags:
              only: /^9.*/
            branches:
              only: /^9.0.x/
